<?php
session_save_path("tmp");
session_start();
$_SESSION['sbx'] = $_POST['sbx'];

$tmpfname = tempnam("tmp", "fegg_".$_SESSION['script']."_");
unlink($tmpfname);

// ==================================================
// Until 5.2.3 a file created with tempnam had relative path.
// After this version the file have absolute path.
// https://bugs.php.net/bug.php?id=43877
$tmpfname = "tmp/" . basename($tmpfname);

setcookie('url', $_SESSION['url'], time()+100*24*60*60);
setcookie('simus', implode(", ",$_SESSION['simus']), time()+100*24*60*60);
setcookie('file', $_SESSION['file'], time()+100*24*60*60);
setcookie('allfiles', implode(", ",$_SESSION['allfiles']), time()+100*24*60*60);
setcookie('script', $_SESSION['script'], time()+100*24*60*60);
setcookie('sbx', $_SESSION['sbx'], time()+100*24*60*60);

?>

<HTML>

<HEAD>

<TITLE>Script <?php print($tmpfname.".jnl"); ?></TITLE>
<script type="text/javascript" src="js/popimage.js"></script>

</HEAD>


<BODY>

<FONT style="font-family: Arial, Helvetica, sans-serif;">
<?php

include $_SESSION['script'].".php";

exec("./runferret $tmpfname ".$_SESSION['file'],$return_code);
//print_r(implode("<BR>\n",$return_code));

?>

<!-- ################################## -->
<B>Resulting image:</B><BR> 
<?php
print("<a href=javascript:popimage(\"$tmpfname.gif\")>");
print("<IMG SRC=\"$tmpfname.gif\">");
print("</a>");
?>

<!-- ################################## -->
<TABLE width=100% border=1><TR>
<TD width=60%>
<B>Download the ferret script run:</B> 
<?php
print("<a href=\"$tmpfname.jnl\">$tmpfname.jnl</a>");
?>
</TD>
<TD ALIGN="left" VALIGN="top" width=40%>
<B><A href="help.html" target="_blank"><FONT color="#ff0000">Help</FONT></A></B>
</TD>
</TR><TR>
<TD>
<B>Download a shell script to run this ferret script for all files:</B>
<?php
$fh = fopen($tmpfname."_prod.bash", "w");
$cmd="#!/bin/bash";
fwrite($fh, $cmd."\n");
$cmd="# Script generated by FEGG (Ferret in an EGG)";
fwrite($fh, $cmd."\n\n");
$cmd="#=====================================";
fwrite($fh, $cmd."\n");
$cmd="#### Please modify if needed";
fwrite($fh, $cmd."\n");
$cmd=". /home/webservices/.atlas_env_webservices_bash   # IPSL (webservices)";
fwrite($fh, $cmd."\n");
$cmd="#. /home/cont003/p86ipsl/.atlas_env_mercure_ksh   # CCRT (mercure)";
fwrite($fh, $cmd."\n");
$cmd="#. /home/rech/psl/rpsl035/.atlas_env_ulam_bash    # IDRIS (ulam)";
fwrite($fh, $cmd."\n");
$cmd="#. /home/users/brock/.atlas_env_asterix_bash      # LSCE (asterix)";
fwrite($fh, $cmd."\n");
$cmd="#. /home/brocksce/.atlas_env_calcul_ksh           # IPSL (calcul2)";
fwrite($fh, $cmd."\n\n");
$cmd="#=====================================";
fwrite($fh, $cmd."\n");
$cmd="#### Please modify if needed";
fwrite($fh, $cmd."\n");
$cmd="scriptname=".$tmpfname.".jnl";
fwrite($fh, $cmd."\n");
$cmd="if ! [[ -f \$scriptname && -s \$scriptname ]] ; then";
fwrite($fh, $cmd."\n");
$cmd="	echo \"Please download the ferret script \$scriptname\"";
fwrite($fh, $cmd."\n");
$cmd="exit";
fwrite($fh, $cmd."\n");
$cmd="fi";
fwrite($fh, $cmd."\n\n");
$cmd="#=====================================";
fwrite($fh, $cmd."\n");
$cmd="colors_keys=( ATM    CHM    ICE    MBG    OCE    SBG    SRF )";
fwrite($fh, $cmd."\n");
$cmd="colors_vals=( AECDFF F0D5F4 D4E3E6 D0F8E0 6D80FF EEE8AA E7FFAB)";
fwrite($fh, $cmd."\n\n");
$cmd="function findcolor() {";
fwrite($fh, $cmd."\n");
$cmd="local i=0";
fwrite($fh, $cmd."\n");
$cmd="while [ \$i -lt \${#colors_keys[*]} ] ; do";
fwrite($fh, $cmd."\n");
$cmd="        if [ \"\${colors_keys[\$i]}\" = \"\$1\" ] ; then";
fwrite($fh, $cmd."\n");
$cmd="                findcolor=\${colors_vals[\$i]}";
fwrite($fh, $cmd."\n");
$cmd="                return 1";
fwrite($fh, $cmd."\n");
$cmd="        fi";
fwrite($fh, $cmd."\n");
$cmd="        let i=i+1";
fwrite($fh, $cmd."\n");
$cmd="done";
fwrite($fh, $cmd."\n");
$cmd="findcolor=FFFFFF";
fwrite($fh, $cmd."\n");
$cmd="return 0";
fwrite($fh, $cmd."\n");
$cmd="}";
fwrite($fh, $cmd."\n\n");
$cmd="#=====================================";
fwrite($fh, $cmd."\n");
$cmd="listfiles=(\\";
fwrite($fh, $cmd."\n");
foreach($_SESSION['allfiles'] as $file1) {
	$cmd="$file1 \\";
	fwrite($fh, $cmd."\n");
}
$cmd=")";
fwrite($fh, $cmd."\n\n");
$cmd="#=====================================";
fwrite($fh, $cmd."\n");
$cmd="outputdir=\${scriptname%%.jnl}_prod/images";
fwrite($fh, $cmd."\n");
$cmd="rm -rf \${outputdir}";
fwrite($fh, $cmd."\n");
$cmd="mkdir -p \${outputdir}";
fwrite($fh, $cmd."\n\n");
$cmd="#=====================================";
fwrite($fh, $cmd."\n");
$cmd="for file in \${listfiles[*]} ; do";
fwrite($fh, $cmd."\n");
$cmd="        echo ferret -batch \${outputdir}/\${file%%.nc}.gif -script \${scriptname} \${file}";
fwrite($fh, $cmd."\n");
$cmd="        ferret -batch \${outputdir}/\${file%%.nc}.gif -script \${scriptname} \${file}";
fwrite($fh, $cmd."\n\n");
$cmd="        prefix=`echo \${file} | cut -f 1 -d _`";
fwrite($fh, $cmd."\n");
$cmd="        findcolor \$prefix";
fwrite($fh, $cmd."\n");
$cmd="        convert -geometry 50%x50% -bordercolor \"#\${findcolor}\" -border 15x15 \${outputdir}/\${file%%.nc}.gif \${outputdir}/\${file%%.nc}.jpg";
fwrite($fh, $cmd."\n");
$cmd="done";
fwrite($fh, $cmd."\n\n");
$cmd="#=====================================";
fwrite($fh, $cmd."\n");
$listsimus=array();
foreach ($_SESSION['simus'] as $s)
	$listsimus[]=basename($s);
$cmd="monitoring01_createindex -t 'Inter-monitoring: ".implode(" vs ", $listsimus)."' \${scriptname%%.jnl}_prod";
fwrite($fh, $cmd."\n\n");
$cmd="#=====================================";
fwrite($fh, $cmd."\n");
$cmd="#### Please modify if needed";
fwrite($fh, $cmd."\n");
$cmd="#cp -fR \${scriptname%%.jnl}_prod /somewhere/dir";
fwrite($fh, $cmd."\n\n");
fclose($fh);

exec("chmod -R 777 tmp/*");

print("<a href=\"".$tmpfname."_prod.bash\" target=\"_blank\">".$tmpfname."_prod.bash</a>\n");
print("</TD>\n");
print("<TD ALIGN=\"left\" VALIGN=\"top\">\n");
print("<form name=\"formprod\" method=\"post\" action=\"prod.php?name=".$tmpfname."\" target=\"_blank\">\n");
print("<input type=\"submit\" value=\"Run this script on the server\" style=\"font-family: Arial, Helvetica, sans-serif;\">\n");
print("</form>\n");
?>
</TD>
</TR></TABLE>


<!-- ################################## -->
<BR>
<TABLE bgcolor="lightyellow" width=100%><TR><TD>
<PRE style="font-family: Arial, Helvetica, sans-serif;">
<?php
$theData=file_get_contents($tmpfname.".jnl");
echo $theData;
?>
</PRE>
</TD></TR></TABLE>

<?php
include("clean.php");
?>

</FONT>
</BODY>
</HTML>
